apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-cluster
  region: ap-south-1

nodeGroups:
  - name: ng-1
    instanceType: t2.micro
    desiredCapacity: 2
    ssh:
       publicKeyName: mykey1122
  - name: ng-2
    instanceType: t2.small
    desiredCapacity: 1
    ssh:
       publicKeyName: mykey1122